import type { Metadata } from "next";
import { Manrope as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "../lib/utils";
import Navbar from "@/components/custom/Navbar";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <Navbar>{children}</Navbar>
      </body>
    </html>
  );
}
